language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
    - "2.7"
    - "3.5"
    - "3.6"
env:
    - DJANGO="django==1.11.9"
    - DJANGO="django==2.0.6"
    - DJANGO="django==2.1"
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="django==2.0.6"
    - python: "2.7"
      env: DJANGO="django==2.1"
  include:
    - python: 3.7
      env: DJANGO="django==2.0.6"
      dist: xenial
      sudo: true
    - python: 3.7
      env: DJANGO="django==2.1"
      dist: xenial
      sudo: true
install:
    - pip install Pillow
    - pip install $DJANGO
    - pip install django-formtools>=1.0
    - pip install django-nose
    - pip install coveralls
script:
    - coverage run --source=db_file_storage demo_and_tests/manage.py test
after_success:
    - coveralls
