language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
env:
    - DJANGO="django==1.6"
    - DJANGO="django==1.7"
    - DJANGO="django==1.8"
install:
    - pip install Pillow
    - pip install $DJANGO
    - pip install coveralls
script:
    coverage run --source=db_file_storage demo_and_tests/manage.py test
after_success:
    coveralls
