language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - DJANGO="django>=1.8,<1.9"
    - DJANGO="django>=1.9,<1.10"
install:
    - pip install Pillow
    - pip install $DJANGO
    - pip install django-formtools>=1.0
    - pip install django-nose
    - pip install coveralls
script:
    - coverage run --source=db_file_storage demo_and_tests/manage.py test
after_success:
    - coveralls
